### ISSUE TITLE
For Faucet I am trying to claim with 3 wallets and getting "error: Error with captcha" Is that because I need 0.001 eth on each wallet or something else 

### ISSUE THREAD

**Issue by khaled-ghn** [BlathanAevon/berachain_multi_actions#4]

**Comment by BlathanAevon** [comment]
Hi, it means that your Capsolver keys is probably wrong or you don’t have enough balance in Capsolver account, please double check everything.

**Comment by khaled-ghn** [comment]
Thanks, I will double check

**Comment by khaled-ghn** [comment]
I want to use free provider to obtain the API key. I know they have rate limit but might do the job. in this case should I only change config.ts or their other related functions I must change as well ?

**Comment by BlathanAevon** [comment]
In case, if you want to use another captcha-solving solution, you will have to change the code in `faucet.ts`, there are methods that are responsible for solving the captcha, there is a simple request, so you can adjust it to your by following the documentation

**Comment by khaled-ghn** [comment]
Thanks 🙏
