### ISSUE TITLE
faucet claim

### ISSUE THREAD

**Issue by Mir89090** [BlathanAevon/berachain_multi_actions#5]
getting error in faucet claim i sign up in capsolver and enter api this getting error

**Comment by BlathanAevon** [comment]
Could you please procvide more detailed information ?

**Comment by Mir89090** [comment]
![Screenshot 2024-10-01 113006](https://github.com/user-attachments/assets/00d450de-ec06-47cf-8bab-2b6cb14dab69)
getting like this always i enter api also

**Comment by BlathanAevon** [comment]
Please check [last issue](https://github.com/BlathanAevon/berachain_multi_actions/issues/4) where it was resolved

**Comment by Mir89090** [comment]
ok can yoi give free caphca site name i do it from there

**Comment by BlathanAevon** [comment]
I don't know free captcha sites, I am using capsolver
